image:
  repository: localhost:5000/python-guestbook-backend
  tag: dev
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  PORT: "8080"
  GUESTBOOK_DB_ADDR: "python-guestbook-mongodb:27017"

ingress:
  enabled: true
  host: localhost
  path: /api

prometheus:
  serviceMonitor: { enabled: true, interval: 30s }
  rule:
    enabled: true
    errorRateThreshold: 0.05