apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels: {{- include "mongodb.labels" . | nindent 2 }}
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-metrics
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  selector:
    app: mongodb
  ports:
    - name: http
      port: 9216
      targetPort: metrics