image:
  repository: localhost:5000/python-guestbook-frontend
  tag: dev
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  PORT: "8080"
  GUESTBOOK_API_ADDR: "backend:80"

ingress:
  enabled: true
  host: localhost  # access via http://localhost (or http://localhost:8080 if your kind mapped 8080)

resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 512Mi }

prometheus:
  serviceMonitor:
    enabled: true
    interval: 30s
  rule:
    enabled: true              # turn alerts on
    errorRateThreshold: 0.05
pdb:
  enabled: true
  minAvailable: 1

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

resourceQuota:
  enabled: false
  requests:
    cpu: "1"
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 2Gi
  pods: "5"
  pvcs: "1"
