apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "backend.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.service.port }}